---
:test:
  :host: localhost
  :question_port: 1234
  :answer_port: 5678
:dev:
  :host: localhost
  :question_port: 1234
  :answer_port: 5678
:prod:
  :host: localhost
  :question_port: 1234
  :answer_port: 5678
